apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-ewck
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-ewck
    app.kubernetes.io/part-of: cin4s-839-0085-app
  name: devfile-sample-ewck
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-ewck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-ewck
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0085-tenant/cin4s-839-0085-app/devfile-sample-ewck@sha256:d7c37e92a5fea8b8a7784cdda2f374bfa2675f442acac25f02099654728a73f5
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
